name: BitAuth
version: 0.0.2
main: bitlegend.bitauth.BitAuth
commands:
    register:
        description: Registers to the server
        usage: /register <password>
    login:
        description: Log in to the server
        usage: /login <password>
    pwreset:
        description: Administrative command, resets a players password and forces a new one to be entered on next login
        usage: /pwreset <username> <password>
    ipcheck:
        description: Enable or disable IP checking on your account
        usage: /ipcheck <enable/disable>
    whitelist:
        description: Administrative command, adds or removes a specified player from the whitelist
        usage: /whitelist <add/del> <username>
    logout:
        description: Terminate your current session, requires the user to log back in to play
        usage: /logout
    unregister:
        description: Can be used to unregister your account or by an administrator to remove the account of another user
        usage: /unregister [username]
    chpasswd:
        description: Used to change your password
        usage: /chpasswd <oldpass> <newpass>
permissions:
    bitauth.*:
        description: Gives access to all BitAuth features
        children:
            bitauth.whitelist: true
    bitauth.whitelist:
        description: Allows you to modify the whitelist
        default: op