name: BitAuth
version: 1.2.2
description: A lightweight authentication plugin. Uses MySQL.
author: dechiridas
website: http://dechiridas.github.com/BitAuth
depend: [PermissionsEx]
main: com.dechiridas.bitauth.BitAuth
commands:
    register:
        description: Registers to the server
        usage: /register <password>
    login:
        description: Log in to the server
        usage: /login <password>
    pwreset:
        description: Administrative command, resets a players password and forces a new one to be entered on next login
        usage: /pwreset <username> <temp password>
    ipcheck:
        description: Enable or disable IP checking on your account
        usage: /ipcheck <enable/disable>
    whitelist:
        description: Administrative command, adds or removes a specified player from the whitelist
        usage: /whitelist <add/del> <username>
    logout:
        description: Terminate your current session, requires the user to log back in to play
        usage: /logout [username]
    unregister:
        description: Can be used to unregister your account or by an administrator to remove the account of another user
        usage: /unregister [username]
    chpasswd:
        description: Used to change your password
        usage: /chpasswd <oldpass> <newpass>
    jumblepw:
        description: Used to permanently disable a user without banning them
        usage: /jumblepw <username>
    baversion:
        description: Retrieve the version number of BitAuth
        usage: /baversion
    iphistory:
        description: Retrieve the last 5 unique IP addresses associated with a user
        usage: /iphistory <user>
        aliases: [history, ips]
permissions:
    bitauth.*:
        description: Gives access to all BitAuth features
        children:
            bitauth.whitelist: true
            bitauth.pwreset: true
            bitauth.logout: true
            bitauth.logout.other: true
            bitauth.iphistory.self: true
            bitauth.iphistory.other: true
    bitauth.whitelist:
        description: Allows you to modify the whitelist
        default: op
    bitauth.pwreset:
        description: Allows you to reset user passwords
        default: op
    bitauth.logout:
        description: Allows you to terminate your current session
        default: op
    bitauth.logout.other:
        description: Allows you to forcefully log another user out
        default: op
    bitauth.jumble:
        description: Allows you to jumble user passwords (disable the user more or less)
        default: op
    bitauth.iphistory.self:
        description: Allows you to check your own IP history
        default: op
    bitauth.iphistory.other:
        description: Allows you to check the IP history of another user
        default: op